### ISSUE TITLE
ER release for SCR v3.0rc1

### ISSUE THREAD

**Issue by gonsie** [ECP-VeloC/er#13]
See SCR v3.0 project: https://github.com/llnl/scr/projects/2

## Process

- [x] Merge any existing PRs
- [x] Create a commit(s) which updates the project version number in the code and updates references to any dependency versions.  
- [x] Merge the commit
- [x] Tag a release on GitHub
- [x] Add release note (can be done after the release is tagged)
- [ ] Update the spack package, both with the version hash and the dependency versions.

**Comment by CamStan** [comment]
Spack package PR: https://github.com/spack/spack/pull/23022
